theme: bulma-clean-theme

# https://www.csrhymes.com/bulma-clean-theme/page-3/
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

title: Harold Meerwaldt
repository: haroldmeerwaldt/haroldmeerwaldt.github.io

# todo: add github API authentication: see e.g. https://github.com/github/pages-gem/issues/399

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      title: "Harold Meerwaldt"
      show_sidebar: false
      menubar: menubar
      hero_height: is-primary
